# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

COPY NetSSO.App1 NetSSO.App1

# RUN dotnet restore
RUN dotnet restore "./NetSSO.App1/NetSSO.App1.csproj" --disable-parallel

RUN dotnet publish "./NetSSO.App1/NetSSO.App1.csproj" -c release -o /app --no-restore

# Serve Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY --from=build /app ./

# EXPOSE 80
# ENTRYPOINT ["dotnet", "NetSSO.App1.dll", "--launch-profile http"]
ENTRYPOINT ["dotnet", "NetSSO.App1.dll"]