version: '3.4'

services:
  sso.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis:IpPort=sso-redis:6379"
      - "Redis:Password=123"
    depends_on:
      - sso.redis
    ports:
      - "8000:8080"

  sso.app1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - "Redis:IpPort=sso-redis:6379"
      - "Redis:Password=123"
    depends_on:
      - sso.redis
      - sso.identity
    ports:
      - "8001:8080"

  sso.nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sso.identity  
      - sso.app1   
    links:
      - sso.identity  
      - sso.app1  
    ports:
      - "9000:80"

  sso.redis:
    # restart: always
    ports:
      - "6379:6379"
    volumes:
      - $HOME/redis/net-sso/d–∞ta:/root/redis
      - $HOME/redis/net-sso/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      #- REDIS_PASSWORD=123
      #- REDIS_DATABASES=16