# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

COPY NetSSO.Identity NetSSO.Identity

# RUN dotnet restore
RUN dotnet restore "./NetSSO.Identity/NetSSO.Identity.csproj" --disable-parallel

RUN dotnet publish "./NetSSO.Identity/NetSSO.Identity.csproj" -c release -o /app --no-restore

# Serve Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY --from=build /app ./

# EXPOSE 80
# ENTRYPOINT ["dotnet", "NetSSO.Identity.dll", "--launch-profile http"]
ENTRYPOINT ["dotnet", "NetSSO.Identity.dll"]